// Generated by CoffeeScript 1.9.0
(function() {
  define(["./bower_components/mathjs/dist/math.js"], function(math) {
    var C, Explanation, laws, scientificNotation;
    C = {
      boltzman1: function() {
        return 3.74e8;
      },
      boltzman2: function() {
        return 1.44e4;
      },
      wien: function() {
        return 2898;
      },
      zeroKelvin: function() {
        return -273.15;
      }
    };
    laws = {
      Planck: function(temperature, wavelength) {
        return C.boltzman1() / ((Math.pow(wavelength, 5)) * (Math.exp(C.boltzman2() / (wavelength * temperature)) - 1));
      },
      Wien: function(temperature) {
        return C.wien() / temperature;
      },
      Celsius: function(kelvin) {
        return math.unit(kelvin, "K").toNumber("degC");
      },
      Fahrenheit: function(kelvin) {
        return math.unit(kelvin, "K").toNumber("degF");
      },
      Rankine: function(kelvin) {
        return math.unit(kelvin, "K").toNumber("degR");
      }
    };
    scientificNotation = function(d) {
      if (!d) {
        return;
      }
      return parseFloat(d).toExponential(1).replace(/^(.*)e([+-])(\d*)$/, function(match, mag, sign, exp) {
        mag = mag === "1.0" ? "" : mag.replace(/\.0$/, "") + "×";
        sign = sign === "-" ? "⁻" : "";
        exp = exp.split("").map(function(e) {
          return "⁰¹²³⁴⁵⁶⁷⁸⁹"[+e];
        }).join("");
        return mag + "10" + sign + exp;
      });
    };
    return Explanation = {
      laws: laws,
      constants: C,
      scientificNotation: scientificNotation,
      math: math
    };
  });

}).call(this);
