// Generated by CoffeeScript 1.9.0
(function() {
  require.config({
    paths: {
      underscore: "./bower_components/underscore/underscore"
    },
    shim: {
      underscore: {
        exports: "_"
      }
    }
  });

  define(["underscore"], function(_) {
    var Fn;
    Fn = function(d3, MathJax) {
      var api, _replacements;
      _replacements = function() {
        return {};
      };
      api = function(selection) {
        return selection.each(function(d, i) {
          var jax;
          d = d || {};
          d.template = d.template || _.template(d3.select(this).text());
          jax = d3.select(this).datum(d).style({
            visibility: "hidden"
          }).text("$$ " + (d.template(_replacements(d))) + " $$");
          return MathJax.Hub.Queue([
            "Typeset", MathJax.Hub, this, function() {
              var preview;
              preview = jax.select(".MathJax_Preview").node();
              if (preview) {
                return jax.style({
                  visibility: "visible"
                });
              }
            }
          ]);
        });
      };
      api.replacements = function(val) {
        if (!!arguments.length) {
          _replacements;
        }
        _replacements = d3.functor(val);
        return api;
      };
      return api;
    };
    return Fn;
  });

}).call(this);
