// Generated by CoffeeScript 1.9.0
(function() {
  define(["./explanation.js"], function(Exp) {
    var Temperatures, converters, d3, domains, labels, padding, references, sliderPadding;
    d3 = null;
    padding = {
      top: 40,
      left: 120,
      right: 120,
      bottom: 90
    };
    sliderPadding = {
      top: 80,
      left: 10,
      right: 10,
      bottom: 110,
      temperature: 40,
      solution: 140
    };
    domains = {
      x: [0, 2000],
      y0: [-500, 2000],
      y1: [-1000, 4000]
    };
    converters = [Exp.laws.Celsius, Exp.laws.Fahrenheit, Exp.laws.Rankine];
    labels = ["Celsius [C]", "Fahrenheit [F]", "Rankine [R]"];
    references = converters.map(function(convert, i) {
      return {
        scaleIdx: i,
        points: domains.x.map(function(k) {
          return [k, convert(k)];
        })
      };
    });
    Temperatures = function(_d3) {
      var api, axes, colorizeLegend, dispatch, plotSeries, scales, seriesPath, useScale;
      d3 = _d3;
      scales = {
        x: d3.scale.linear().domain(domains.x),
        y0: d3.scale.linear().domain(domains.y0),
        y1: d3.scale.linear().domain(domains.y1),
        color: d3.scale.ordinal().range(["green", "red", "blue"])
      };
      axes = {
        x: d3.svg.axis().scale(scales.x).orient('bottom'),
        y0: d3.svg.axis().scale(scales.y0).orient('left'),
        y1: d3.svg.axis().scale(scales.y1).orient('right')
      };
      seriesPath = function(y) {
        return d3.svg.line().x(function(d) {
          return scales.x(d[0]);
        }).y(function(d) {
          return y(d[1]);
        });
      };
      useScale = [scales.y0, scales.y1, scales.y1];
      plotSeries = function(series) {
        return series.call(function(series) {
          return series.enter().append("g").classed({
            series: true
          }).append("path").style({
            stroke: function(d, i) {
              return scales.color(i);
            }
          });
        }).selectAll("path").attr({
          d: function(d) {
            var fn;
            fn = seriesPath(useScale[d.scaleIdx]);
            return fn(d.points);
          }
        });
      };
      colorizeLegend = function(d, i) {
        if (i) {
          return scales.color(i - 1);
        } else {
          return "black";
        }
      };
      dispatch = d3.dispatch("update");
      api = function(selection) {
        var TEMPERATURE, clip, defs, el_xAxis, el_y0Axis, el_y1Axis, plots, plotsBg, solutions, svg, xLabel, y0Label, y1Label;
        selection.classed({
          explanation: true,
          temperatures: true
        });
        TEMPERATURE = 0;
        api.explore = function() {
          var mouseX, mouseY, _ref;
          _ref = d3.mouse(this), mouseX = _ref[0], mouseY = _ref[1];
          TEMPERATURE = Math.min(domains.x[1], Math.max(scales.x.invert(mouseX), domains.x[0]));
          return api.update();
        };
        api.update = function() {
          var scaleSolutions;
          scaleSolutions = converters.map(function(convert) {
            return [TEMPERATURE, convert(TEMPERATURE)];
          });
          dispatch.update({
            K: TEMPERATURE,
            C: scaleSolutions[0][1],
            F: scaleSolutions[1][1],
            R: scaleSolutions[2][1]
          });
          svg.selectAll(".solution.interactive").data([[TEMPERATURE, scaleSolutions[0][1]], [TEMPERATURE, scaleSolutions[1][1]], [TEMPERATURE, scaleSolutions[2][1]]]).call(function(solutionLabel) {
            return solutionLabel.enter().append("g").classed({
              solution: true,
              interactive: true
            }).append("line").style({
              stroke: function(d, i) {
                return ["green", "red", "blue"][i];
              }
            }).attr({
              x1: 0,
              y1: 0,
              x2: function(d, i) {
                if (i === 0) {
                  return 20;
                } else {
                  return -20;
                }
              },
              y2: 0,
              "marker-start": function(d, i) {
                return "url(#end-arrow-" + (scales.color(i)) + ")";
              }
            });
          }).attr({
            transform: function(d, i) {
              if (i === 0) {
                return "translate(" + padding.left + ", " + (scales.y0(d[1])) + ")";
              } else {
                return "translate(" + (scales.x.range()[1]) + ", " + (scales.y1(d[1])) + ")";
              }
            }
          }).select("text").text(function(d, i) {
            return 'KCFR'[i] + " = " + (d[1].toFixed(2));
          });
          plots.select(".scanline path").datum([[scales.x(TEMPERATURE), scales.y0.range()[0]], [scales.x(TEMPERATURE), scales.y0.range()[1]]]).attr({
            d: d3.svg.line()
          });
          solutions.attr({
            transform: "translate(" + (padding.left + 2 * padding.top) + ", " + (2 * padding.top) + ")"
          }).selectAll(".solution.legend").data([[TEMPERATURE, TEMPERATURE]].concat(scaleSolutions)).call(function(solution) {
            solution.enter().append("g").classed({
              solution: true,
              legend: true
            }).call(function(solution) {
              solution.append("text").classed({
                scale: true
              }).attr({
                dx: 10
              });
              return solution.append("text").classed({
                value: true
              }).attr("text-anchor", "end");
            });
            solution.attr({
              transform: function(d, i) {
                return "translate(0 " + (i * 30) + ")";
              }
            });
            solution.select(".scale").text(function(d, i) {
              return ["Kelvin [K]"].concat(labels)[i];
            }).style({
              fill: colorizeLegend
            });
            return solution.select(".value").text(function(d, i) {
              return d[1].toFixed(2);
            }).style({
              fill: colorizeLegend
            });
          });
          return api;
        };
        api.resize = function(event) {
          var HEIGHT, WIDTH;
          WIDTH = selection.node().clientWidth;
          HEIGHT = selection.node().clientHeight;
          scales.x.range([padding.left, WIDTH - padding.right]);
          scales.y1.range([HEIGHT - padding.bottom, padding.top]);
          scales.y0.range([HEIGHT - padding.bottom, padding.top]);
          svg.attr({
            width: WIDTH,
            height: HEIGHT
          });
          plotsBg.attr({
            width: WIDTH - padding.right,
            height: HEIGHT
          });
          clip.attr({
            width: WIDTH,
            height: scales.y0.range()[0],
            x: 0
          });
          el_xAxis.attr({
            transform: "translate(0, " + (HEIGHT - padding.bottom) + ")"
          }).call(axes.x);
          el_y0Axis.attr({
            transform: "translate(" + padding.left + ", 0)"
          }).call(axes.y0);
          el_y1Axis.attr({
            transform: "translate(" + (WIDTH - padding.right) + ", 0)"
          }).call(axes.y1);
          xLabel.attr({
            transform: "translate(" + [WIDTH / 2, HEIGHT - 50] + ")"
          });
          y0Label.attr({
            transform: "translate(10, " + (HEIGHT / 2) + ") rotate(-90)"
          });
          y1Label.attr({
            transform: "translate(" + (WIDTH - 10) + ", " + (HEIGHT / 2) + ") rotate(90)"
          });
          plots.selectAll('.series').data(references).call(plotSeries);
          return api.update();
        };
        svg = selection.selectAll(".plot").data([1]).call(function(svg) {
          svg = svg.enter().append("svg").classed({
            plot: true
          });
          svg.append("defs").call(function(defs) {
            defs.append("clipPath").classed({
              "temperatures-path": true
            }).attr({
              id: "temperaturesPath"
            }).append("rect");
            return defs.selectAll("marker").data(scales.color.range()).enter().append("marker").attr({
              id: function(d) {
                return "end-arrow-" + d;
              },
              viewBox: "0 -5 10 10",
              markerWidth: 6,
              markerHeight: 6,
              orient: "auto"
            }).append("path").attr({
              d: "M 10,-5 L 0,0 L 10,5"
            }).style({
              fill: Object
            });
          });
          svg.append("g").classed({
            plots: true
          }).attr({
            "clip-path": "url(#temperaturesPath)"
          }).call(function(plots) {
            plots.append("rect").classed({
              bg: true
            }).on({
              mousemove: api.explore
            });
            plots.append("g").classed({
              solutions: true
            });
            return plots.append("g").classed({
              scanline: true
            }).append("path");
          });
          svg.append("g").classed({
            axis: true,
            x: true
          });
          svg.append("g").classed({
            axis: true,
            y0: true
          });
          svg.append("g").classed({
            axis: true,
            y1: true
          });
          svg.append("g").classed({
            label: true,
            y0: true
          }).append("text").attr({
            "text-anchor": "middle",
            dy: ".71em"
          }).call(function(yLabel) {
            yLabel.append("tspan").classed({
              "fill-celsius": true
            }).text("Celsius");
            yLabel.append("tspan").classed({
              unit: true
            }).text(" [");
            yLabel.append("tspan").classed({
              "fill-celsius": true
            }).text("C");
            return yLabel.append("tspan").classed({
              unit: true
            }).text("]");
          });
          svg.append("g").classed({
            label: true,
            y1: true
          }).append("text").attr({
            "text-anchor": "middle",
            dy: ".71em"
          }).call(function(yLabel) {
            yLabel.append("tspan").text("Fahrenheit ").classed({
              "fill-fahrenheit": true
            });
            yLabel.append("tspan").text("Rankine").classed({
              "fill-rankine": true
            });
            yLabel.append("tspan").classed({
              unit: true
            }).text(" [");
            yLabel.append("tspan").classed({
              "fill-fahrenheit": true
            }).text("F");
            yLabel.append("tspan").classed({
              unit: true
            }).text(",");
            yLabel.append("tspan").classed({
              "fill-rankine": true
            }).text("R");
            return yLabel.append("tspan").classed({
              unit: true
            }).text("]");
          });
          return svg.append("g").classed({
            label: true,
            x: true
          }).append("text").attr({
            "text-anchor": "middle",
            dy: ".71em",
            y: -10
          }).call(function(xLabel) {
            xLabel.append("tspan").text("Kelvin");
            xLabel.append("tspan").classed({
              unit: true
            }).text(" [");
            xLabel.append("tspan").classed({
              "fill-kelvin": true
            }).text("K");
            return xLabel.append("tspan").classed({
              unit: true
            }).text("]");
          });
        });
        plots = svg.select(".plots");
        solutions = plots.select(".solutions");
        plotsBg = plots.select(".bg");
        defs = svg.select("defs");
        clip = defs.select(".temperatures-path rect");
        el_xAxis = svg.select(".axis.x");
        el_y0Axis = svg.select(".axis.y0");
        el_y1Axis = svg.select(".axis.y1");
        xLabel = svg.select(".label.x text");
        y0Label = svg.select(".label.y0 text");
        y1Label = svg.select(".label.y1 text");
        d3.select(window).on({
          "resize.temperatures": api.resize
        });
        return api.resize();
      };
      api.dispatch = dispatch;
      return api;
    };
    return Temperatures;
  });

}).call(this);
